### PR TITLE
Fix implementation of Path::endsWith(String)

### LINKED ISSUE #52: endsWith implementation is wrong (w.r.t. API)
If a path such `http://example.com/foo/bar` is tested for `endsWith("/bar")`, the contract of [Path::endsWith](https://docs.oracle.com/javase/8/docs/api/java/nio/file/Path.html#endsWith-java.lang.String-) says that it should return false; in our case, it returns true.

### PR DESCRIPTION
**Pull request by magicDGS**
Fixes #52

### CODE REVIEW

File: src/main/java/org/magicdgs/http/jsr203/HttpPath.java [hunk 1]
```diff
@@ -239,12 +240,9 @@ private boolean endsWith(final byte[] other) {
             }
         }
 
-        // TODO: this codepath is not exercised at all because we always have
-        // TODO: absolute paths, and thus the first statement is always true
-        // TODO: this will change in the future (https://github.com/magicDGS/jsr203-http/issues/12)
         // final check for name boundary
-        return other[olast + 1] == HttpUtils.HTTP_PATH_SEPARATOR_CHAR
-                || last == -1 || this.normalizedPath[last] == HttpUtils.HTTP_PATH_SEPARATOR_CHAR;
+        return last == -1 || this.normalizedPath[last] == HttpUtils.HTTP_PATH_SEPARATOR_CHAR ||
```
Comment (magicDGS) [inline src/main/java/org/magicdgs/http/jsr203/HttpPath.java]: This is too convoluted - should clean the implementation and fix it (it is wrong). Also, requires more tests

File: src/test/java/org/magicdgs/http/jsr203/HttpPathUnitTest.java [hunk 2]
```diff
@@ -142,16 +142,26 @@ public void testStartsWithDifferentProvider() {
...
+    }
+
+    @Test
+    public void testEndsWithStringAbsolutePath() {
+        final Path path = TEST_FS.getPath("/foo/bar");
+        // following the contract, "http://example.com/foo/bar".endsWith("/bar") should return false
+        Assert.assertFalse(path.endsWith("/bar"));
+        // but if I understood correctly, if it endsWith("/foo/bar") should return true
+        Assert.assertTrue(path.endsWith("/foo/bar"));
+        // TODO: should the next statement also return true?
```
Comment (magicDGS) [inline src/test/java/org/magicdgs/http/jsr203/HttpPathUnitTest.java]: Also open an issue to check if this is necessary (and link here)

Comment (magicDGS) [reply src/test/java/org/magicdgs/http/jsr203/HttpPathUnitTest.java]: Better remove by now and get this in soon
